version: "3"

volumes:
  mysql-data: {}

services:
  # http://localhost:16686
  jaeger:
    image: jaegertracing/all-in-one:1.17.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
