[server]
port = 9000

[tracer]
type = "jaeger" # none, jaeger, datadog

[tracer.jaeger]
service_name = "service-name"
collector_endpoint = "http://127.0.0.1:14268/api/traces"
sampling_probability = 1.0  # 0.001 would be fine in production

[tracer.datadog]
service_name = "service-datadog"
collector_endpoint = ":8126"
sampling_probability = 1.0  # 0.001 would be fine in production
